# Generated by Django 3.2.7 on 2023-02-20 21:02

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='primary key id')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+2348189999999', max_length=30, region=None, verbose_name='Your Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
    ]
