# Generated by Django 3.2.7 on 2023-02-24 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='num_reveiews',
            new_name='num_reviews',
        ),
    ]
