#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

postgres_ready(){
python << END
import sys
import psycopg2
try:
	pyscopg2.connect(
		dbname="${POSTGRES_NAME}",
		user = "${POSTGRES_USER}",
		password = "${POSTGRES_PASSWORD}",
		host = "${POSTGRES_PORT}",
		port = "${POSTGRES_PORT}",
	)
except psycopg2.OperationalError:
	sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
 >& echo "[*] waiting for postgresql to become available :("
 sleep 1
done

>& echo "[+] Postgres is ready :)"

exec "$@"